---

- name: Configure vars basis on Logstash version
  set_fact:
    logstash_apt_repo: "{{ item.0.apt_repo }}"
    logstash_repo_key: "{{ item.0.repo_key }}"
    logstash_new_way_configure: "{{ item.0.new_way_configure }}"
    logstash_home: "{{ item.0.home_dir }}"
    logstash_plugin_bin: "{{ item.0.plugin_bin }}"
    logstash_config_validate_params: "{{ item.0.config_validate_params }}"
  with_subelements:
    - "{{ logstash_custom_vars }}"
    - version
  when: item.1 == logstash_version

- name: Enable Logstash Repository
  apt_repository:
    repo: "{{ logstash_apt_repo }}"
    state: present

- name: Add Logstash Repo Key
  apt_key:
    url: "{{ logstash_repo_key }}"
    state: present

- name: Update cache for use last logstash version
  apt:
    update_cache: yes

- name: Install Logstash
  environment:
    LS_JAVA_OPTS: "{{ logstash_java_opts }}"
  apt:
    pkg: "logstash=1:{{ logstash_version }}.*"
    allow_unauthenticated: yes
  register: install_logstash
  notify:
   - reenable logstash.service
   - start logstash

- name: Configure default settings for Logstash
  template:
    src: defaults.conf.j2
    dest: "{{ defaults_Debian }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  when: logstash_new_way_configure == "false"
  notify:
   - reenable logstash.service
   - restart logstash
