---

- name: Generate startup.options file
  template:
    src: etc/logstash/startup.options.j2
    dest: "{{ logstash_settings_dir }}startup.options"
    owner: root
    group: root
    mode: 0644
  notify:
   - setup logstash service
   - reenable logstash.service
   - restart logstash

- name: Generate jvm.options file
  template:
    src: etc/logstash/jvm.options.j2
    dest: "{{ logstash_settings_dir }}jvm.options"
    owner: root
    group: root
    mode: 0644
  notify:
   - restart logstash

- name: Generate log4j2 properties file
  template:
    src: etc/logstash/log4j2.properties.j2
    dest: "{{ logstash_settings_dir }}log4j2.properties"
    owner: root
    group: root
    mode: 0644
  notify:
   - restart logstash
